package proj.p1.models;

public enum ReimbursementTokenType {
	PENDING_EMPLOYEE_REQUESTS, RESOLVED_EMPLOYEE_REQUESTS, 
	REQUEST_BY_ID,	ACCEPT_REQUEST, DECLINE_REQUEST,
	ALL_PENDING_REQUESTS,
	CREATE_REQUEST
}
